//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesment2APITrue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int ClientId { get; set; }
        public int TourEventId { get; set; }
        public string TourName { get; set; }
        public Nullable<int> Payment { get; set; }
        public string DateBooked { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual TourEvent TourEvent { get; set; }
    }
}
